title: Modernist theme
description: Modernist is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist
title: [Jacob Leitch's portfolio]
description: [To showcase current skills and projects to my future employer.]
